# Generated by Django 4.2.4 on 2023-11-27 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_equipment_expense_field_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='dam',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='sex',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='sire',
            field=models.CharField(default='default_dam', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestock',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
