# Generated by Django 4.2.4 on 2023-10-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ultrasound_results', models.TextField()),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancy_events', to='Livestocks.pregnancyevent')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('tag_number', models.CharField(max_length=20, unique=True)),
                ('health_status', models.CharField(max_length=100)),
                ('vaccination_records', models.TextField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='Livestocks.livestock')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='Livestocks.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='CalvingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calving_events', to='Livestocks.calvingevent')),
                ('offspring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_event', to='Livestocks.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_events', to='Livestocks.breedingevent')),
                ('sire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_events', to='Livestocks.breedingevent')),
            ],
        ),
    ]
