# Generated by Django 4.2.4 on 2023-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livestocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='sex',
        ),
        migrations.AlterField(
            model_name='livestock',
            name='breed',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='vaccination_records',
            field=models.CharField(max_length=30),
        ),
    ]
