# Generated by Django 4.2.4 on 2023-11-27 16:02

import Livestocks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Livestocks', '0002_remove_livestock_sex_alter_livestock_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='dam',
            field=models.ForeignKey(blank=True, default=Livestocks.models.Livestock.default_dam, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='Livestocks.livestock'),
        ),
    ]
